#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UsbSerialExampleApp.Resource", IsApplication=true)]

namespace UsbSerialExampleApp
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Hoho.Android.UsbSerial.Resource.String.ApplicationName = global::UsbSerialExampleApp.Resource.String.ApplicationName;
			global::Hoho.Android.UsbSerial.Resource.String.Hello = global::UsbSerialExampleApp.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int consoleText = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int demoScroller = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int demoTitle = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int deviceList = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int progressBar = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int progressBarTitle = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int separator = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int sleepButton = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int wakeupButton = 2130837512;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int serial_console = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7F040003
			public const int refreshing = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int sleep = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int wakeup = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F050000
			public const int device_filter = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
